version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nest
      POSTGRES_PASSWORD: 123456
    ports:
      - 5434:5432
    networks:
      - learn-sql

  hasura:
    image: hasura/graphql-engine:latest
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:123456@postgres:5432/nest
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    ports:
      - 8080:8080
    networks:
      - learn-sql
   
  learn-gql:
    container_name: learn-gql
    build: 
      context: .
      target: development
    volumes:
      - ./:/usr/src/app/
    command: npm run start:dev 
    networks:
      - learn-sql

networks:
  learn-sql: